// constants.js

/**
 * 每次无限滚动加载的数据条目数量。
 */
export const BATCH_SIZE = 80;

/**
 * 当电影或人物海报缺失时使用的占位符图片 (SVG Base64)。
 */
export const placeholderImage = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxODAiIGhlaWdodD0iMjcwIiB2aWV3Qm94PSIwIDAgMTgwIDI3MCI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iIzFlMWUxZSIvPjx0ZXh0IHg9IjUwJSIgeT0iNTAlIiBmaWxsPSIjN2Y3ZjdmIiBmb250LXNpemU9IjE2cHgiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGFsaWdubWVudC1iYXNlbGluZT0ibWlkZGxlIiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiI+Tm8gSW1hZ2U8L3RleHQ+PC9zdmc+';

/**
 * 当演员头像缺失时使用的占位符图片 (SVG Base64)。
 */
export const placeholderActor = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiB2aWV3Qm94PSIwIDAgMTAwIDEwMCI+PGNpcmNsZSBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIGZpbGw9IiMzMzMiLz48cGF0aCBkPSJNNTAsNTBDNTAsMzUgNjUsMjAgNjUsMjBTNTEsMzUgNTEsNTBDNTEsNjUgMzUsODAgMzUsODBTNzUsNjUgNzUsNTBaTTUwLDYwQTM4LDM4IDAgMCAwIDUwLDYwWiIgZmlsbD0iIzY2NiIvPjwvc3ZnPg==';